export const HOME_FEED_DATA_LOADING = 'HOME_FEED_DATA_LOADING';
export const HOME_FEED_DATA_SUCCESS = 'HOME_FEED_DATA_SUCCESS';
export const HOME_FEED_DATA_ERROR = 'HOME_FEED_DATA_LOADED';

export const MOVIE_FEED_DATA_LOADING = 'MOVIE_FEED_DATA_LOADING';
export const MOVIE_FEED_DATA_SUCCESS = 'MOVIE_FEED_DATA_SUCCESS';
export const MOVIE_FEED_DATA_ERROR = 'MOVIE_FEED_DATA_ERROR';
export const SEARCH_MOVIE_LOADING = 'SEARCH_MOVIE_LOADING';
export const SEARCH_MOVIE_LOADING_SUCCESS = 'SEARCH_MOVIE_LOADING_SUCCESS';
export const SEARCH_MOVIE_LOADING_ERROR = 'SEARCH_MOVIE_LOADING_ERROR';
